# Generated by Django 5.1.6 on 2025-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='space',
            field=models.IntegerField(default=0),
        ),
    ]
