# Generated by Django 5.1.6 on 2025-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
