# Generated by Django 5.2 on 2025-05-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scholarship_hours',
            new_name='horas_requeridas',
        ),
    ]
