# Generated by Django 5.2 on 2025-05-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_scholarship_hours_profile_horas_requeridas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='horas_requeridas',
        ),
    ]
