# Generated by Django 5.2 on 2025-05-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_profile_horas_requeridas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university_career',
            field=models.CharField(blank=True, choices=[('Biomédica', 'Biomédica'), ('Biotecnología Industrial', 'Biotecnología Industrial'), ('Ciencia de la Administración', 'Ciencia de la Administración'), ('Ciencias de Alimentos', 'Ciencias de Alimentos'), ('Ciencias de Alimentos Industrial', 'Ciencias de Alimentos Industrial'), ('Civil', 'Civil'), ('Civil Arquitectónica', 'Civil Arquitectónica'), ('Ciencia de la Computación y Tecnologías de la Información', 'Ciencia de la Computación y Tecnologías de la Información'), ('Electrónica', 'Electrónica'), ('Industrial', 'Industrial'), ('Mecánica', 'Mecánica'), ('Mecánica Industrial', 'Mecánica Industrial'), ('Mecatrónica', 'Mecatrónica'), ('Química', 'Química'), ('Química Industrial', 'Química Industrial'), ('Ingeniería en Ciencia de la Administración', 'Ingeniería en Ciencia de la Administración'), ('Administración de Empresas', 'Administración de Empresas'), ('International Marketing and Business Analytics', 'International Marketing and Business Analytics'), ('Comunicación Estratégica', 'Comunicación Estratégica'), ('Profesorado de Enseñanza Media especializado en Educación Musical', 'Profesorado de Enseñanza Media especializado en Educación Musical'), ('Profesorado de Enseñanza Media especializado en English Language Teaching (ELT)', 'Profesorado de Enseñanza Media especializado en English Language Teaching (ELT)'), ('Profesorado Especializado en Educación Inclusiva', 'Profesorado Especializado en Educación Inclusiva'), ('Profesorado Especializado en Educación Primaria (100% virtual)', 'Profesorado Especializado en Educación Primaria (100% virtual)'), ('Profesorado Especializado en Problemas del Aprendizaje', 'Profesorado Especializado en Problemas del Aprendizaje'), ('Profesorado de Enseñanza Media Especializado en Matemática y Ciencias Físicas', 'Profesorado de Enseñanza Media Especializado en Matemática y Ciencias Físicas'), ('Profesorado de Enseñanza Media Especializado en Ciencias Químicas y Biológicas', 'Profesorado de Enseñanza Media Especializado en Ciencias Químicas y Biológicas'), ('Profesorado de Enseñanza Media Especializado en Ciencias Sociales', 'Profesorado de Enseñanza Media Especializado en Ciencias Sociales'), ('Profesorado de Enseñanza Media Especializado en Comunicación y Lenguaje', 'Profesorado de Enseñanza Media Especializado en Comunicación y Lenguaje'), ('Baccalaureatus en Artibus', 'Baccalaureatus en Artibus'), ('Baccalaureatus en Scientiis', 'Baccalaureatus en Scientiis'), ('Arquitectura', 'Arquitectura'), ('Biología', 'Biología'), ('Bioquímica y Microbiología', 'Bioquímica y Microbiología'), ('Biotecnología Molecular', 'Biotecnología Molecular'), ('Física', 'Física'), ('Matemática Aplicada', 'Matemática Aplicada'), ('Nutrición', 'Nutrición'), ('Química', 'Química'), ('Química Farmacéutica', 'Química Farmacéutica'), ('Antropología', 'Antropología'), ('Arqueología', 'Arqueología'), ('Psicología', 'Psicología'), ('Relaciones Internacionales', 'Relaciones Internacionales'), ('Composición y Producción Musical', 'Composición y Producción Musical'), ('Diseño de Producto e Innovación', 'Diseño de Producto e Innovación')], max_length=100, null=True),
        ),
    ]
